[package]
name = "greynet"
edition = "2021"
version = "0.1.0"
authors = ["CameleoGrey (Egor Chnegov) <cameleogrey@yandex.ru>"]
repository = "https://github.com/CameleoGrey/greyjack-solver-rust/"
documentation = "https://github.com/CameleoGrey/greyjack-solver-rust/"
description = "High performance rule and constraint satisfaction engine"
license = "MIT OR Apache-2.0"
keywords = ["greynet", "rule-engine", "rule", "rules", "engine", "greyjack", "solver"]
categories = [
    "mathematics",
	"science",
    "algorithms",
    "data-structures",
	"web-programming"
]

[dependencies]
uuid = { workspace = true }
slotmap = { workspace = true }
generational-arena = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
