[package]
name = "greyjack"
edition = "2021"
version = "0.5.0"
authors = ["CameleoGrey (Egor Chnegov) <cameleogrey@yandex.ru>"]
repository = "https://github.com/CameleoGrey/greyjack-solver-rust/"
documentation = "https://github.com/CameleoGrey/greyjack-solver-rust/"
description = "Rust version of GreyJack Solver for constraint continuous, integer, mixed integer optimization problems"
license = "MIT OR Apache-2.0"
keywords = ["greyjack", "solver", "optimization", "metaheuristic", "polars"]
categories = [
    "mathematics",
	"science",
    "algorithms",
    "data-structures",
	"web-programming"
]

[dependencies]
greyjack-core = { path = "../greyjack-core" }
greynet = { path = "../greynet" }