[package]
name = "nqueens"
version = "0.1.0"
edition = "2021"

[dependencies]
greysplanner = { path = "../greysplanner" }
rand = "0.8.5"
rand_distr = "0.4.3"
polars = { version = "0.45.1", features = ["lazy", "ndarray"] }
ndarray = "0.16.1"