[package]
name = "vrp"
version = "0.4.5"
edition = "2021"
workspace = "../"
publish = false

[dependencies]
greyjack = {path = "../../greyjack"}
polars = { version = "0.46.0", features = ["lazy", "ndarray", "partition_by", "abs"] }
regex = "1.11.1"
serde_json = "1.0.137"
rayon = "1.10.0"